"""Add logo field to Tool model

Revision ID: 254ea151674e
Revises: c58827ef9fb3
Create Date: 2025-01-23 17:26:38.947082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254ea151674e'
down_revision = 'c58827ef9fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.drop_column('logo')

    # ### end Alembic commands ###
